//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFEFWFV05221018
{
    using System;
    using System.Collections.Generic;
    
    public partial class PET
    {
        public int PetID { get; set; }
        public string PetName { get; set; }
        public string PetType { get; set; }
        public string PetBreed { get; set; }
        public Nullable<System.DateTime> PetDOB { get; set; }
        public int OwnerID { get; set; }
    
        public virtual PET_OWNER PET_OWNER { get; set; }
    }
}
