//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFEFWFV05221018
{
    using System;
    using System.Collections.Generic;
    
    public partial class VETERIAN
    {
        public int VetID { get; set; }
        public string VetLastName { get; set; }
        public string VetFirstName { get; set; }
        public string VetPhone { get; set; }
        public string VetEmail { get; set; }
    }
}
